apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: bundlesfolder
      mountPath: /var/data
    ports:
    - containerPort: 80
  volumes:
  - name: bundlesfolder
    #persistentVolumeClaim:
      # claimName: local-path-pvc
      #claimName: longhorn-volv-pvc      
    hostPath:
      # directory location on host
      path: /var/bundles-folder
      # this field is optional
      type: Directory      